### ISSUE TITLE
Unable to create user when calling communication library from premises

### ISSUE THREAD

**Issue by hemchudgar** [Azure/Communication#200]
Calling createUser() method generates below error. I have replaced my connection string with 'CONNECTION_STRING' and endpoint with 'ENDPOINT'. Token generating process works in open network but throws error when tried to generate from premises closed network

FetchError: request to https://ENDPOINT_URL/identities?api-version=2020-07-20-preview2 failed, reason: connect EACCES 13.107.213.19:443
    at ClientRequest.<anonymous> (D:\Demo\access-tokens-quickstart\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:311:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  message: 'request to https://ENDPOINT_URL/identities?api-version=2020-07-20-preview2 failed, reason: connect EACCES 13.107.213.19:443',
  type: 'system',
  errno: 'EACCES',
  code: 'EACCES'
}

Find the below code 

```
const { CommunicationIdentityClient } = require('@azure/communication-administration');

const main = async () => {
    console.log("Azure Communication Services - Access Tokens Quickstart")

    // Quickstart code goes here
    // This code demonstrates how to fetch your connection string
    // from an environment variable.
    const connectionString = 'CONNECTIONSTRING';

    // Instantiate the identity client
    const identityClient = new CommunicationIdentityClient(connectionString);

    let identityResponse = await identityClient.createUser();
    console.log(`\nCreated an identity : ${identityResponse}`);
    console.log(`\nCreated an identity with ID: ${identityResponse.communicationUserId}`);
    // Issue an access token with the "voip" scope for an identity
    let tokenResponse = await identityClient.issueToken(identityResponse, ["voip"]);
    const { token, expiresOn } = tokenResponse;
    console.log(`\nIssued an access token with 'voip' scope that expires at ${expiresOn}:`);
    console.log(token);
};

main().catch((error) => {
    console.log("Encountered an error");
    console.log(error);
})

```

**Comment by DominikMe** [comment]
Hi @hemchudgar, thanks for reaching out!

> Token generating process works in open network but throws error when tried to generate from **premises closed network**

> eason: connect EACCES 13.107.213.19:443',
type: 'system',
errno: 'EACCES',
code: 'EACCES'

Do you have a configuration that forbids your process to make requests to outbound services? The SDK needs to be able to reach your Azure Communication Services resource.

Also, could you try updating to use `@azure/communication-identity`? This new package replaces the `@azure/communication-administration` package.

**Comment by hemchudgar** [comment]
Hi @DominikMe, I tried replacing @azure/communication-administration package with @azure/communication-identity but the same issue persist.

I'm implementing this code using a proxy server and the endpoint URL is already whitelisted.

**Comment by tomaschladek** [comment]
Hi @hemchudgar, were you able to resolve the issue? Is there anything we can do to help you onboard?

We will close this thread within a week if we don't hear back from you.

**Comment by mariusu-msft** [comment]
Closing due to inactivity.
