### ISSUE TITLE
The video stream from the camera is going back slowly (delayed around 15 sec) for the participant who turns off the screen share

### ISSUE THREAD

**Issue by lpx1989** [Azure/Communication#319]
This is bug witnessed when doing debugging session with Calling SDK team @kagbakpem which has already been confirmed. Create a GitHub issue for tracking purpose.

**To Reproduce**
Based on our debugging session, we witnessed that:
1. Turn on screen share from one participant (works fine)
2. Turn off screen share (works fine)
3. The video stream from this specific participant's camera was showing up with a delay around 15 sec. (The video stream from other participants showed up right away as expected)

**Expected behavior**
The video stream from the participant's camera who turns off screen share can going back without a delay.

**Smartphone (please complete the following information):**
 - Device: Pixel4a
 - OS: Android 11

**Comment by RinaRish** [comment]
[AB#2490045](https://skype.visualstudio.com/SPOOL/_workitems/edit/2490045)

**Comment by kagbakpem** [comment]
This should be resolved now, @lpx1989. Can you please test on the latest SDK version: 1.2.0-beta.1 and re-open this if the issue persists?

**Comment by lpx1989** [comment]
Sure I will do some testing with 1.2.0-beta.1 and update my testing result. @kagbakpem

**Comment by lpx1989** [comment]
`lling.RemoteVideoStream.OnVideoStatusChangedStaticHandler(RemoteVideoStream.java:100)
        at com.azure.android.communication.calling.NativeLibrary.sam_remote_video_stream_set_on_video_status_changed(Native Method)
        at com.azure.android.communication.calling.RemoteVideoStream.addOnVideoStatusChangedListener(RemoteVideoStream.java:121)
        at com.azure.android.communication.calling.RemoteVideoStream.restoreEventHandlers(RemoteVideoStream.java:166)
        at com.azure.android.communication.calling.RemoteVideoStream.<init>(RemoteVideoStream.java:46)
        at com.azure.android.communication.calling.ProjectedObjectFactory.create(ProjectedObjectFactory.java:68)
        at com.azure.android.communication.calling.ProjectedObjectCache.getOrCreate(ProjectedObjectCache.java:110)
        at com.azure.android.communication.calling.RemoteVideoStream.getInstancesCollection(RemoteVideoStream.java:159)
        at com.azure.android.communication.calling.RemoteVideoStream.OnVideoStatusChangedStaticHandler(RemoteVideoStream.java:100)
        at com.azure.android.communication.calling.NativeLibrary.sam_remote_video_stream_set_on_video_status_changed(Native Method)
        at com.azure.android.communication.calling.RemoteVideoStream.addOnVideoStatusChangedListener(RemoteVideoStream.java:121)
        at com.azure.android.communication.calling.RemoteVideoStream.restoreEventHandlers(RemoteVideoStream.java:166)
        at com.azure.android.communication.calling.RemoteVideoStream.<init>(RemoteVideoStream.java:46)
        at com.azure.android.communication.calling.ProjectedObjectFactory.create(ProjectedObjectFactory.java:68)
        at com.azure.android.communication.calling.ProjectedObjectCache.getOrCreate(ProjectedObjectCache.java:110)
E/AndroidRuntime:     at com.azure.android.communication.calling.RemoteVideoStream.getInstancesCollection(RemoteVideoStream.java:159)
        at com.azure.android.communication.calling.RemoteVideoStream.OnVideoStatusChangedStaticHandler(RemoteVideoStream.java:100)
        at com.azure.android.communication.calling.NativeLibrary.sam_remote_video_stream_set_on_video_status_changed(Native Method)
        at com.azure.android.communication.calling.RemoteVideoStream.addOnVideoStatusChangedListener(RemoteVideoStream.java:121)
        at com.azure.android.communication.calling.RemoteVideoStream.restoreEventHandlers(RemoteVideoStream.java:166)
        at com.azure.android.communication.calling.RemoteVideoStream.<init>(RemoteVideoStream.java:46)
        at com.azure.android.communication.calling.ProjectedObjectFactory.create(ProjectedObjectFactory.java:68)
        at com.azure.android.communication.calling.ProjectedObjectCache.getOrCreate(ProjectedObjectCache.java:110)
        at com.azure.android.communication.calling.RemoteVideoStream.getInstancesCollection(RemoteVideoStream.java:159)
        at com.azure.android.communication.calling.RemoteVideoStream.OnVideoStatusChangedStaticHandler(RemoteVideoStream.java:100)
        at com.azure.android.communication.calling.NativeLibrary.sam_remote_video_stream_set_on_video_status_changed(Native Method)
        at com.azure.android.communication.calling.RemoteVideoStream.addOnVideoStatusChangedListener(RemoteVideoStream.java:121)
        at com.azure.android.communication.calling.RemoteVideoStream.restoreEventHandlers(RemoteVideoStream.java:166)
        at com.azure.android.communication.calling.RemoteVideoStream.<init>(RemoteVideoStream.java:46)
        at com.azure.android.communication.calling.ProjectedObjectFactory.create(ProjectedObjectFactory.java:68)
        at com.azure.android.communication.calling.ProjectedObjectCache.getOrCreate(ProjectedObjectCache.java:110)
        at com.azure.android.communication.calling.RemoteVideoStream.getInstancesCollection(RemoteVideoStream.java:159)
        at com.azure.android.communication.calling.RemoteVideoStream.OnVideoStatusChangedStaticHandler(RemoteVideoStream.java:100)
        at com.azure.android.communication.calling.NativeLibrary.sam_remote_video_stream_set_on_video_status_changed(Native Method)
        at com.azure.android.communication.calling.RemoteVideoStream.addOnVideoStatusChangedListener(RemoteVideoStream.java:121)
        at com.azure.android.communication.calling.RemoteVideoStream.restoreEventHandlers(RemoteVideoStream.java:166)
        at com.azure.android.communication.calling.RemoteVideoStream.<init>(RemoteVideoStream.java:46)
        at com.azure.android.communication.calling.ProjectedObjectFactory.create(ProjectedObjectFactory.java:68)
        at com.azure.android.communication.calling.ProjectedObjectCache.getOrCreate(ProjectedObjectCache.java:110)
        at com.azure.android.communication.calling.RemoteVideoStream.getInstancesCollection(RemoteVideoStream.java:159)
        at com.azure.android.communication.calling.RemoteVideoStream.OnVideoStatusChangedStaticHandler(RemoteVideoStream.java:100)
        at com.azure.android.communication.calling.NativeLibrary.sam_remote_video_stream_set_on_video_status_changed(Native Method)
        at com.azure.android.communication.calling.RemoteVideoStream.addOnVideoStatusChangedListener(RemoteVideoStream.java:121)
        at com.azure.android.communication.calling.RemoteVideoStream.restoreEventHandlers(RemoteVideoStream.java:166)
        at com.azure.android.communication.calling.RemoteVideoStream.<init>(RemoteVideoStream.java:46)
        at com.azure.android.communication.calling.ProjectedObjectFactory.create(ProjectedObjectFactory.java:68)
        at com.azure.android.communication.calling.ProjectedObjectCache.getOrCreate(ProjectedObjectCache.java:110)
        at com.azure.android.communication.calling.RemoteVideoStream.getInstancesCollection(RemoteVideoStream.java:159)
        at com.azure.android.communication.calling.RemoteVideoStream.OnVideoStatusChangedStaticHandler(RemoteVideoStream.java:100)
        at com.azure.android.communication.calling.NativeLibrary.sam_remote_video_stream_set_on_video_status_changed(Native Method)
        at com.azure.android.communication.calling.RemoteVideoStream.addOnVideoStatusChangedListener(RemoteVideoStream.java:121)
        at com.azure.android.communication.calling.RemoteVideoStream.restoreEventHandlers(RemoteVideoStream.java:166)
        at com.azure.android.communication.calling.RemoteVideoStream.<init>(RemoteVideoStream.java:46)
        at com.azure.android.communication.calling.ProjectedObjectFactory.create(ProjectedObjectFactory.java:68)
        at com.azure.android.communication.calling.ProjectedObjectCache.getOrCreate(ProjectedObjectCache.java:110)
        at com.azure.android.communication.calling.RemoteVideoStream.getInstancesCollection(RemoteVideoStream.java:159)
        at com.azure.android.communication.calling.RemoteVideoStream.OnVideoStatusChangedStaticHandler(RemoteVideoStream.java:100)
        at com.azure.android.communication.calling.NativeLibrary.sam_remote_video_stream_set_on_video_status_changed(Native Method)
        at com.azure.android.communication.calling.RemoteVideoStream.addOnVideoStatusChangedListener(RemoteVideoStream.java:121)
        at com.azure.android.communication.calling.RemoteVideoStream.restoreEventHandlers(RemoteVideoStream.java:166)
        at com.azure.android.communication.calling.RemoteVideoStream.<init>(RemoteVideoStream.java:46)
        at com.azure.android.communication.calling.ProjectedObjectFactory.create(ProjectedObjectFactory.java:68)
        at com.azure.android.communication.calling.ProjectedObjectCache.getOrCreate(ProjectedObjectCache.java:110)
        at com.azure.android.communication.calling.RemoteVideoStream.getInstancesCollection(RemoteVideoStream.java:159)
        at com.azure.android.communication.calling.RemoteVideoStream.OnVideoStatusChangedStaticHandler(RemoteVideoStream.java:100)
        at com.azure.android.communication.calling.NativeLibrary.sam_remote_video_stream_set_on_video_status_changed(Native Method)
        at com.azure.android.communication.calling.RemoteVideoStream.addOnVideoStatusChangedListener(RemoteVideoStream.java:121)
        at com.azure.android.communication.calling.RemoteVideoStream.restoreEventHandlers(RemoteVideoStream.java:166)
        at com.azure.android.communication.calling.RemoteVideoStream.<init>(RemoteVideoStream.java:46)
        at com.azure.android.communication.calling.ProjectedObjectFactory.create(ProjectedObjectFactory.java:68)
        at com.azure.android.communication.calling.ProjectedObjectCache.getOrCreate(ProjectedObjectCache.java:110)
        at com.azure.android.communication.calling.RemoteVideoStream.getInstancesCollection(RemoteVideoStream.java:159)
        at com.azure.android.communication.calling.RemoteVideoStream.OnVideoStatusChangedStaticHandler(RemoteVideoStream.java:100)
        at com.azure.android.communication.calling.NativeLibrary.sam_remote_video_stream_set_on_video_status_changed(Native Method)
        at com.azure.android.communication.calling.RemoteVideoStream.addOnVideoStatusChangedListener(RemoteVideoStream.java:121)
        at com.azure.android.communication.calling.RemoteVideoStream.restoreEventHandlers(RemoteVideoStream.java:166)
        at com.azure.android.communication.calling.RemoteVideoStream.<init>(RemoteVideoStream.java:46)
        at com.azure.android.communication.calling.ProjectedObjectFactory.create(ProjectedObjectFactory.java:68)
        at com.azure.android.communication.calling.ProjectedObjectCache.getOrCreate(ProjectedObjectCache.java:110)
        at com.azure.android.communication.calling.RemoteVideoStream.getInstancesCollection(RemoteVideoStream.java:159)
        at com.azure.android.communication.calling.RemoteVideoStream.OnVideoStatusChangedStaticHandler(RemoteVideoStream.java:100)
        at com.azure.android.communication.calling.NativeLibrary.sam_remote_video_stream_set_on_video_status_changed(Native Method)
        at com.azure.android.communication.calling.RemoteVideoStream.addOnVideoStatusChangedListener(RemoteVideoStream.java:121)
        at com.azure.android.communication.calling.RemoteVideoStream.restoreEventHandlers(RemoteVideoStream.java:166)
        at com.azure.android.communication.calling.RemoteVideoStream.<init>(RemoteVideoStream.java:46)
        at com.azure.android.communication.calling.ProjectedObjectFactory.create(ProjectedObjectFactory.java:68)
        at com.azure.android.communication.calling.ProjectedObjectCache.getOrCreate(ProjectedObjectCache.java:110)
        at com.azure.android.communication.calling.RemoteVideoStream.getInstancesCollection(RemoteVideoStream.java:159)
        at com.azure.android.communication.calling.RemoteVideoStream.OnVideoStatusChangedStaticHandler(RemoteVideoStream.java:100)
        at com.azure.android.communication.calling.NativeLibrary.sam_remote_video_stream_set_on_video_status_changed(Native Method)
        at com.azure.android.communication.calling.RemoteVideoStream.addOnVideoStatusChangedListener(RemoteVideoStream.java:121)
        at com.azure.android.communication.calling.RemoteVideoStream.restoreEventHandlers(RemoteVideoStream.java:166)
        at com.azure.android.communication.calling.RemoteVideoStream.<init>(RemoteVideoStream.java:46)
        at com.azure.android.communication.calling.ProjectedObjectFactory.create(ProjectedObjectFactory.java:68)
        at com.azure.android.communication.calling.ProjectedObjectCache.getOrCreate(ProjectedObjectCache.java:110)
        at com.azure.android.communication.calling.RemoteVideoStream.getInstancesCollection(RemoteVideoStream.java:159)
        at com.azure.android.communication.calling.RemoteVideoStream.OnVideoStatusChangedStaticHandler(RemoteVideoStream.java:100)
        at com.azure.android.communication.calling.NativeLibrary.sam_remote_video_stream_set_on_video_status_changed(Native Method)
        at com.azure.android.communication.calling.RemoteVideoStream.addOnVideoStatusChangedListener(RemoteVideoStream.java:121)
        at com.azure.android.communication.calling.RemoteVideoStream.restoreEventHandlers(RemoteVideoStream.java:166)
        at com.azure.android.communication.calling.RemoteVideoStream.<init>(RemoteVideoStream.java:46)
        at com.azure.android.communication.calling.ProjectedObjectFactory.create(ProjectedObjectFactory.java:68)
        at com.azure.android.communication.calling.ProjectedObjectCache.getOrCreate(ProjectedObjectCache.java:110)
        at com.azure.android.communication.calling.RemoteVideoStream.getInstancesCollection(RemoteVideoStream.java:159)
        at com.azure.android.communication.calling.RemoteVideoStream.OnVideoStatusChangedStaticHandler(RemoteVideoStream.java:100)
        at com.azure.android.communication.calling.NativeLibrary.sam_remote_video_stream_set_on_video_status_changed(Native Method)
        at com.azure.android.communication.calling.RemoteVideoStream.addOnVideoStatusChangedListener(RemoteVideoStream.java:121)
        at com.azure.android.communication.calling.RemoteVideoStream.restoreEventHandlers(RemoteVideoStream.java:166)
        at com.azure.android.communication.calling.RemoteVideoStream.<init>(RemoteVideoStream.java:46)
        at com.azure.android.communication.calling.ProjectedObjectFactory.create(ProjectedObjectFactory.java:68)
        at com.azure.android.communication.calling.ProjectedObjectCache.getOrCreate(ProjectedObjectCache.java:110)
        at com.azure.android.communication.calling.RemoteVideoStream.getInstancesCollection(RemoteVideoStream.java:159)
        at com.azure.android.communication.calling.RemoteVideoStream.OnVideoStatusChangedStaticHandler(RemoteVideoStream.java:100)
        at com.azure.android.communication.calling.NativeLibrary.sam_remote_video_stream_set_on_video_status_changed(Native Method)
        at com.azure.android.communication.calling.RemoteVideoStream.addOnVideoStatusChangedListener(RemoteVideoStream.java:121)
        at com.azure.android.communication.calling.RemoteVideoStream.restoreEventHandlers(RemoteVideoStream.java:166)
        at com.azure.android.communication.calling.RemoteVideoStream.<init>(RemoteVideoStream.java:46)
        at com.azure.android.communication.calling.ProjectedObjectFactory.create(ProjectedObjectFactory.java:68)
        at com.azure.android.communication.calling.ProjectedObjectCache.getOrCreate(ProjectedObjectCache.java:110)
        at com.azure.android.communication.calling.RemoteVideoStream.getInstancesCollection(RemoteVideoStream.java:159)
`

**Comment by lpx1989** [comment]
After testing, I got error shown above. what I did is: join few participants from web clients into the call with the user from mobile client. let one of participant from web client share the screen. afterwards, stop the screen sharing. then the error was showing up. @kagbakpem

**Comment by kagbakpem** [comment]
@lpx1989, which version of the SDK are you using?
