### ISSUE TITLE
Android: com.azure.android:azure-communication-calling failed: errno 28 No space left on device

### ISSUE THREAD

**Issue by iaulakh** [Azure/Communication#352]
**Describe the bug**
After running call for sometime, application crashes with"errno 28 No space left on device"

```
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: GLTextureView
    Process: com.azure.android.communication.ui, PID: 12859
    com.skype.android.video.render.EGLException: EGL error: 12291 eglCreateContext
        at com.skype.android.video.render.EGL10RenderSurface.check(EGL10RenderSurface.java:107)
        at com.skype.android.video.render.EGL10RenderSurface.create(EGL10RenderSurface.java:64)
        at com.skype.android.video.render.GLTextureView._createSurface(GLTextureView.java:270)
        at com.skype.android.video.render.GLTextureView.handleMessage(GLTextureView.java:120)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**To Reproduce**
1. Start call
2. Join with 6 participants video on and 6 participants with audio only
3. Unmute all
4. After sometime application crashes with above error message

Memory while crashing:
![Screen Shot 2021-08-09 at 9 16 32 AM](https://user-images.githubusercontent.com/73618019/128739170-4927fbe9-c0c1-4898-983b-18bb8dd9da01.png)

**Desktop (please complete the following information):**
 - OS: Android 11

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4a

https://skype.visualstudio.com/SPOOL/_workitems/edit/2540286

**Comment by jsaurezlee-msft** [comment]
AB#2540286

**Comment by jaime-carpintero** [comment]
@jsaurezlee-msft  based on the extra information that was provided by Inderpal, we proceed to conduct an in-depth test based on the following:

Physical device was being used (Pixel 4a)
Potential SDK version used at the time: 1.2.0-beta.2
error: No space left on device should be output on android studio's logcat
Average time to reproduce is between 30min~40min
Participants were toggling video on/off
No profiler was attached to the device
Conducting test using physical device to see if this bug is still present.

**Comment by jsaurezlee-msft** [comment]
Closing as per @jaime-carpintero investigation: 

> Test were conducted based on extra information provided by the user.
> 
> Test were performed with the following ACS calling SDK versions:
> azure-communication-calling-1.2.0
> azure-communication-calling-1.2.0-beta.2
> azure-communication-calling-1.2.1-beta.1
> 
> being unable to replicate the issue described. closing issue.

**Comment by mariusu-msft** [comment]
Reopening based on feedback from @iaulakh

**Comment by iaulakh** [comment]
@jaime-carpintero would it be possible to reopen-github issue?
