### ISSUE TITLE
[C# | Chat] Error 400 when trying to create a huge chat thread

### ISSUE THREAD

**Issue by btmpn** [Azure/Communication#379]
Hi,

i just wrote a test function to figure out how our application handles the maximum size of a chat thread (250 users).

Initially I created 248 azure communication users.
After that I wrote code to create a chat thread with my personal user, and the just created 248 users to get a chat thread with 249 members.

I used
```cs
chatClient.CreateChatThread(topic, participants);
```
where topic contains my topic (`string`), and participants contains 249 users (`List<ChatParticipant>`).

This was not possible - i got the following error:

```
Azure.RequestFailedException: Service request failed.
Status: 400 (Bad Request)

Content:
{
  "CommunicationError": {
    "Code": "BadRequest",
    "Details": []
  }
}

Headers:
Transfer-Encoding: chunked
MS-CV: QWXBhA+AB0qcxHMOGLZLzw.0
Strict-Transport-Security: REDACTED
api-supported-versions: REDACTED
X-Processing-Time: REDACTED
x-ms-client-request-id: a471f995-5f72-401b-a4f6-41b7f38f0c77
X-Cache: REDACTED
X-Azure-Ref: REDACTED
Date: Thu, 16 Sep 2021 10:34:05 GMT
Content-Type: application/json

   at Azure.Communication.Chat.ChatRestClient.CreateChatThread(String topic, String repeatabilityRequestId, IEnumerable`1 participants, CancellationToken cancellationToken)
   at Azure.Communication.Chat.ChatClient.CreateChatThread(String topic, IEnumerable`1 participants, String idempotencyToken, CancellationToken cancellationToken)
```

Is this a bug, or did I something wrong?
Maybe it isn't possible to create a chatthread with 249 members at once?

Thanks in advance!

**Comment by btmpn** [comment]
Additional information:

we found out that this problem does not only exist when trying to create a new (big) chat thread.
It also crashes with the same/similar error when trying to add a big amount of users at once to an existing chat thread, with:

```cs
chatClient.AddParticipants(participants);
```

So it seems that there is a limitation of the request size?
